# <?php exit; ?>

- backend:
  MAIL_CHARSET:   UTF-8   #编码
  MAIL_AUTH:      true   #邮箱认证
  MAIL_HTML:      true   #true HTML格式 false TXT格式
  TMPL_EXCEPTION_FILE: ./server/Tpl/exception.html
  LANG: zh-cn
  - preloadJSDebug:
    - "vendor/jquery/jquery-2.1.3.min.js"
    - "vendor/angular-1.3.0-rc/angular.min.js"
    - "vendor/bootstrap.min.js"
    - "vendor/angular-1.3.0-rc/angular-resource.min.js"
    - "vendor/angular-1.3.0-rc/angular-cookies.min.js"
    - "vendor/angular-1.3.0-rc/angular-sanitize.min.js"
    - "vendor/angular-1.3.0-rc/angular-route.min.js"
    - "vendor/angular-1.3.0-rc/angular-touch.min.js"
    - "vendor/angular-1.3.0-rc/angular-animate.min.js"
    - "vendor/angularModules/angular-strap/angular-strap.js"
    - "vendor/angularModules/angular-strap/angular-strap.tpl.js"
    - "vendor/angularModules/ui-utils/ui-utils.min.js"
    - "vendor/angularModules/angular-chosen/chosen.js"
    - "base/config.js"
    - "vendor/AdminLTE/AdminLTE.js"
    - "vendor/metisMenu/metisMenu.min.js"
    - "vendor/sb-admin-2/sb-admin-2.js"
    - "vendor/highcharts/highstock.js" 
    - "vendor/highcharts/ng-highcharts.js"
    - "lib/caches.js"
    - "lib/plugin.js"
    - "lib/function.js"
    - "lib/print.js"
    - "base/filter.js"
    - "base/service.js"
    - "base/plugin.js"
  - preloadJS:
    - "vendor/jquery/jquery-2.1.1.min.js"
    - "vendor/angular-1.3.0-rc/angular.min.js"
    - "vendor/bootstrap.min.js"
    - "vendor/angular-1.3.0-rc/angular-resource.min.js"
    - "vendor/angular-1.3.0-rc/angular-cookies.min.js"
    - "vendor/angular-1.3.0-rc/angular-sanitize.min.js"
    - "vendor/angular-1.3.0-rc/angular-route.min.js"
    - "vendor/angular-1.3.0-rc/angular-touch.min.js"
    - "vendor/angular-1.3.0-rc/angular-animate.min.js"
    - "vendor/angularModules/angular-strap/angular-strap.min.js"
    - "vendor/angularModules/angular-strap/angular-strap.tpl.min.js"
    - "vendor/angularModules/ui-utils/ui-utils.min.js"
    - "vendor/angularModules/angular-chosen/chosen.js"
    - "base/config.js"
    - "vendor/AdminLTE/AdminLTE.js"
    - "lib/caches.js"
    - "lib/plugin.js"
    - "lib/function.js"
    - "lib/print.js"
    - "base/filter.js"
    - "base/service.js"
    - "base/plugin.js"
